/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { BaseHttpRequest } from './core/BaseHttpRequest';
import type { OpenAPIConfig } from './core/OpenAPI';
import { AxiosHttpRequest } from './core/AxiosHttpRequest';
import { AbsenceService } from './services/AbsenceService';
import { AbsencesService } from './services/AbsencesService';
import { AbsenceTypeService } from './services/AbsenceTypeService';
import { AvailabilityService } from './services/AvailabilityService';
import { CompanyService } from './services/CompanyService';
import { CompanyAddressUsersService } from './services/CompanyAddressUsersService';
import { CompanyCandidateService } from './services/CompanyCandidateService';
import { CompanyCandidateEventService } from './services/CompanyCandidateEventService';
import { CompanyCandidateEventMeetingService } from './services/CompanyCandidateEventMeetingService';
import { CompanyCandidateEventMeetingsService } from './services/CompanyCandidateEventMeetingsService';
import { CompanyCandidateEventNoteService } from './services/CompanyCandidateEventNoteService';
import { CompanyCandidateEventNotesService } from './services/CompanyCandidateEventNotesService';
import { CompanyCandidateEventsService } from './services/CompanyCandidateEventsService';
import { CompanyCandidateEventTaskService } from './services/CompanyCandidateEventTaskService';
import { CompanyCandidateEventTasksService } from './services/CompanyCandidateEventTasksService';
import { CompanyCandidateFileAttachmentService } from './services/CompanyCandidateFileAttachmentService';
import { CompanyCandidateFileAttachmentsService } from './services/CompanyCandidateFileAttachmentsService';
import { CompanyCandidatePipelinesService } from './services/CompanyCandidatePipelinesService';
import { CompanyCandidatesService } from './services/CompanyCandidatesService';
import { CompanyCandidateSkillsService } from './services/CompanyCandidateSkillsService';
import { CompanyCandidateUriAttachmentService } from './services/CompanyCandidateUriAttachmentService';
import { CompanyCandidateUriAttachmentsService } from './services/CompanyCandidateUriAttachmentsService';
import { CompanyCandidateUserService } from './services/CompanyCandidateUserService';
import { CompanyCapabilitiesService } from './services/CompanyCapabilitiesService';
import { CompanyCurrenciesService } from './services/CompanyCurrenciesService';
import { CompanyCustomerService } from './services/CompanyCustomerService';
import { CompanyCustomerAddressService } from './services/CompanyCustomerAddressService';
import { CompanyCustomerContactService } from './services/CompanyCustomerContactService';
import { CompanyCustomerContactsService } from './services/CompanyCustomerContactsService';
import { CompanyCustomerContactTagsService } from './services/CompanyCustomerContactTagsService';
import { CompanyCustomerEventService } from './services/CompanyCustomerEventService';
import { CompanyCustomerEventsService } from './services/CompanyCustomerEventsService';
import { CompanyCustomerEventsMeetingService } from './services/CompanyCustomerEventsMeetingService';
import { CompanyCustomerEventsMeetingsService } from './services/CompanyCustomerEventsMeetingsService';
import { CompanyCustomerEventsNoteService } from './services/CompanyCustomerEventsNoteService';
import { CompanyCustomerEventsNotesService } from './services/CompanyCustomerEventsNotesService';
import { CompanyCustomerEventsTaskService } from './services/CompanyCustomerEventsTaskService';
import { CompanyCustomerEventsTasksService } from './services/CompanyCustomerEventsTasksService';
import { CompanyCustomerFileAttachmentService } from './services/CompanyCustomerFileAttachmentService';
import { CompanyCustomerManagersService } from './services/CompanyCustomerManagersService';
import { CompanyCustomersService } from './services/CompanyCustomersService';
import { CompanyCustomersExtendedService } from './services/CompanyCustomersExtendedService';
import { CompanyCustomerTagsService } from './services/CompanyCustomerTagsService';
import { CompanyImageService } from './services/CompanyImageService';
import { CompanyImagesService } from './services/CompanyImagesService';
import { CompanyManagersService } from './services/CompanyManagersService';
import { CompanyProfilesService } from './services/CompanyProfilesService';
import { CompanyProjectFileAttachmentService } from './services/CompanyProjectFileAttachmentService';
import { CompanyRecruitmentManagersService } from './services/CompanyRecruitmentManagersService';
import { CompanyResumesService } from './services/CompanyResumesService';
import { CompanySubcontractorGroupService } from './services/CompanySubcontractorGroupService';
import { CompanySubcontractorGroupMembersService } from './services/CompanySubcontractorGroupMembersService';
import { CompanySubcontractorGroupsService } from './services/CompanySubcontractorGroupsService';
import { CompanyTagService } from './services/CompanyTagService';
import { CompanyTagsService } from './services/CompanyTagsService';
import { CompanyTeamService } from './services/CompanyTeamService';
import { CompanyTeamManagersService } from './services/CompanyTeamManagersService';
import { CompanyTeamMemberService } from './services/CompanyTeamMemberService';
import { CompanyTeamMembersService } from './services/CompanyTeamMembersService';
import { CompanyTeamsService } from './services/CompanyTeamsService';
import { CompanyTeamUsersService } from './services/CompanyTeamUsersService';
import { CompanyUserService } from './services/CompanyUserService';
import { CompanyUserConvertService } from './services/CompanyUserConvertService';
import { CompanyUserEmployeeEventService } from './services/CompanyUserEmployeeEventService';
import { CompanyUserEmployeeEventMeetingService } from './services/CompanyUserEmployeeEventMeetingService';
import { CompanyUserEmployeeEventNoteService } from './services/CompanyUserEmployeeEventNoteService';
import { CompanyUserEmployeeEventsService } from './services/CompanyUserEmployeeEventsService';
import { CompanyUserEmployeeEventsMeetingsService } from './services/CompanyUserEmployeeEventsMeetingsService';
import { CompanyUserEmployeeEventsNotesService } from './services/CompanyUserEmployeeEventsNotesService';
import { CompanyUserEmployeeEventsTasksService } from './services/CompanyUserEmployeeEventsTasksService';
import { CompanyUserEmployeeEventTaskService } from './services/CompanyUserEmployeeEventTaskService';
import { CompanyUserFullService } from './services/CompanyUserFullService';
import { CompanyUserPermissionsService } from './services/CompanyUserPermissionsService';
import { CompanyUserProfileService } from './services/CompanyUserProfileService';
import { CompanyUserProfileCommitmentService } from './services/CompanyUserProfileCommitmentService';
import { CompanyUserProfileEducationService } from './services/CompanyUserProfileEducationService';
import { CompanyUserProfileEmployerService } from './services/CompanyUserProfileEmployerService';
import { CompanyUserProfileExtSkillService } from './services/CompanyUserProfileExtSkillService';
import { CompanyUserProfileImportService } from './services/CompanyUserProfileImportService';
import { CompanyUserProfileLanguageService } from './services/CompanyUserProfileLanguageService';
import { CompanyUserProfileLanguagesService } from './services/CompanyUserProfileLanguagesService';
import { CompanyUserProfilePresentationService } from './services/CompanyUserProfilePresentationService';
import { CompanyUserProfileReferenceService } from './services/CompanyUserProfileReferenceService';
import { CompanyUserProfilesService } from './services/CompanyUserProfilesService';
import { CompanyUserProfileSkillService } from './services/CompanyUserProfileSkillService';
import { CompanyUserProfileTrainingService } from './services/CompanyUserProfileTrainingService';
import { CompanyUserProfileWorkExperienceService } from './services/CompanyUserProfileWorkExperienceService';
import { CompanyUserResumeService } from './services/CompanyUserResumeService';
import { CompanyUserResumesService } from './services/CompanyUserResumesService';
import { CompanyUserRolesService } from './services/CompanyUserRolesService';
import { CompanyUsersService } from './services/CompanyUsersService';
import { CompanyUsersExtendedService } from './services/CompanyUsersExtendedService';
import { CompanyUserSkillService } from './services/CompanyUserSkillService';
import { CompanyUserSkillsService } from './services/CompanyUserSkillsService';
import { CompanyUserSubcontractorService } from './services/CompanyUserSubcontractorService';
import { CompanyUserSubcontractorEventService } from './services/CompanyUserSubcontractorEventService';
import { CompanyUserSubcontractorEventMeetingService } from './services/CompanyUserSubcontractorEventMeetingService';
import { CompanyUserSubcontractorEventNoteService } from './services/CompanyUserSubcontractorEventNoteService';
import { CompanyUserSubcontractorEventsService } from './services/CompanyUserSubcontractorEventsService';
import { CompanyUserSubcontractorEventsMeetingsService } from './services/CompanyUserSubcontractorEventsMeetingsService';
import { CompanyUserSubcontractorEventsNotesService } from './services/CompanyUserSubcontractorEventsNotesService';
import { CompanyUserSubcontractorEventsTasksService } from './services/CompanyUserSubcontractorEventsTasksService';
import { CompanyUserSubcontractorEventTaskService } from './services/CompanyUserSubcontractorEventTaskService';
import { CompanyUserSubcontractorFileAttachmentService } from './services/CompanyUserSubcontractorFileAttachmentService';
import { CompanyUserSubcontractorFileAttachmentsService } from './services/CompanyUserSubcontractorFileAttachmentsService';
import { CompanyUserSubcontractorRolesService } from './services/CompanyUserSubcontractorRolesService';
import { CompanyUserSubcontractorsService } from './services/CompanyUserSubcontractorsService';
import { CompanyUserTagsService } from './services/CompanyUserTagsService';
import { CompanyUserTeamsService } from './services/CompanyUserTeamsService';
import { CompanyWebhookService } from './services/CompanyWebhookService';
import { CompanyWebhooksService } from './services/CompanyWebhooksService';
import { DynamicCompanyUserResumeService } from './services/DynamicCompanyUserResumeService';
import { KeywordSearchService } from './services/KeywordSearchService';
import { MentionsService } from './services/MentionsService';
import { PartnersService } from './services/PartnersService';
import { ProjectService } from './services/ProjectService';
import { ProjectAssignmentService } from './services/ProjectAssignmentService';
import { ProjectAssignmentMemberService } from './services/ProjectAssignmentMemberService';
import { ProjectAssignmentsService } from './services/ProjectAssignmentsService';
import { ProjectAssignmentSkillsService } from './services/ProjectAssignmentSkillsService';
import { ProjectEventService } from './services/ProjectEventService';
import { ProjectEventsService } from './services/ProjectEventsService';
import { ProjectEventsMeetingService } from './services/ProjectEventsMeetingService';
import { ProjectEventsMeetingsService } from './services/ProjectEventsMeetingsService';
import { ProjectEventsNoteService } from './services/ProjectEventsNoteService';
import { ProjectEventsNotesService } from './services/ProjectEventsNotesService';
import { ProjectEventsTaskService } from './services/ProjectEventsTaskService';
import { ProjectEventsTasksService } from './services/ProjectEventsTasksService';
import { ProjectPipelinesService } from './services/ProjectPipelinesService';
import { ProjectReferenceService } from './services/ProjectReferenceService';
import { ProjectReferencesService } from './services/ProjectReferencesService';
import { ProjectsService } from './services/ProjectsService';
import { ProjectTagsService } from './services/ProjectTagsService';
import { RecruitmentSourcesService } from './services/RecruitmentSourcesService';
import { SearchCompanyCandidateService } from './services/SearchCompanyCandidateService';
import { SearchCompanyCustomerContactService } from './services/SearchCompanyCustomerContactService';
import { SearchCompanyCustomersService } from './services/SearchCompanyCustomersService';
import { SearchCompanyUserService } from './services/SearchCompanyUserService';
import { SearchProjectService } from './services/SearchProjectService';
import { SkillSearchService } from './services/SkillSearchService';
import { SkillSearchTermService } from './services/SkillSearchTermService';
type HttpRequestConstructor = new (config: OpenAPIConfig) => BaseHttpRequest;
export class Cinode {
    public readonly absence: AbsenceService;
    public readonly absences: AbsencesService;
    public readonly absenceType: AbsenceTypeService;
    public readonly availability: AvailabilityService;
    public readonly company: CompanyService;
    public readonly companyAddressUsers: CompanyAddressUsersService;
    public readonly companyCandidate: CompanyCandidateService;
    public readonly companyCandidateEvent: CompanyCandidateEventService;
    public readonly companyCandidateEventMeeting: CompanyCandidateEventMeetingService;
    public readonly companyCandidateEventMeetings: CompanyCandidateEventMeetingsService;
    public readonly companyCandidateEventNote: CompanyCandidateEventNoteService;
    public readonly companyCandidateEventNotes: CompanyCandidateEventNotesService;
    public readonly companyCandidateEvents: CompanyCandidateEventsService;
    public readonly companyCandidateEventTask: CompanyCandidateEventTaskService;
    public readonly companyCandidateEventTasks: CompanyCandidateEventTasksService;
    public readonly companyCandidateFileAttachment: CompanyCandidateFileAttachmentService;
    public readonly companyCandidateFileAttachments: CompanyCandidateFileAttachmentsService;
    public readonly companyCandidatePipelines: CompanyCandidatePipelinesService;
    public readonly companyCandidates: CompanyCandidatesService;
    public readonly companyCandidateSkills: CompanyCandidateSkillsService;
    public readonly companyCandidateUriAttachment: CompanyCandidateUriAttachmentService;
    public readonly companyCandidateUriAttachments: CompanyCandidateUriAttachmentsService;
    public readonly companyCandidateUser: CompanyCandidateUserService;
    public readonly companyCapabilities: CompanyCapabilitiesService;
    public readonly companyCurrencies: CompanyCurrenciesService;
    public readonly companyCustomer: CompanyCustomerService;
    public readonly companyCustomerAddress: CompanyCustomerAddressService;
    public readonly companyCustomerContact: CompanyCustomerContactService;
    public readonly companyCustomerContacts: CompanyCustomerContactsService;
    public readonly companyCustomerContactTags: CompanyCustomerContactTagsService;
    public readonly companyCustomerEvent: CompanyCustomerEventService;
    public readonly companyCustomerEvents: CompanyCustomerEventsService;
    public readonly companyCustomerEventsMeeting: CompanyCustomerEventsMeetingService;
    public readonly companyCustomerEventsMeetings: CompanyCustomerEventsMeetingsService;
    public readonly companyCustomerEventsNote: CompanyCustomerEventsNoteService;
    public readonly companyCustomerEventsNotes: CompanyCustomerEventsNotesService;
    public readonly companyCustomerEventsTask: CompanyCustomerEventsTaskService;
    public readonly companyCustomerEventsTasks: CompanyCustomerEventsTasksService;
    public readonly companyCustomerFileAttachment: CompanyCustomerFileAttachmentService;
    public readonly companyCustomerManagers: CompanyCustomerManagersService;
    public readonly companyCustomers: CompanyCustomersService;
    public readonly companyCustomersExtended: CompanyCustomersExtendedService;
    public readonly companyCustomerTags: CompanyCustomerTagsService;
    public readonly companyImage: CompanyImageService;
    public readonly companyImages: CompanyImagesService;
    public readonly companyManagers: CompanyManagersService;
    public readonly companyProfiles: CompanyProfilesService;
    public readonly companyProjectFileAttachment: CompanyProjectFileAttachmentService;
    public readonly companyRecruitmentManagers: CompanyRecruitmentManagersService;
    public readonly companyResumes: CompanyResumesService;
    public readonly companySubcontractorGroup: CompanySubcontractorGroupService;
    public readonly companySubcontractorGroupMembers: CompanySubcontractorGroupMembersService;
    public readonly companySubcontractorGroups: CompanySubcontractorGroupsService;
    public readonly companyTag: CompanyTagService;
    public readonly companyTags: CompanyTagsService;
    public readonly companyTeam: CompanyTeamService;
    public readonly companyTeamManagers: CompanyTeamManagersService;
    public readonly companyTeamMember: CompanyTeamMemberService;
    public readonly companyTeamMembers: CompanyTeamMembersService;
    public readonly companyTeams: CompanyTeamsService;
    public readonly companyTeamUsers: CompanyTeamUsersService;
    public readonly companyUser: CompanyUserService;
    public readonly companyUserConvert: CompanyUserConvertService;
    public readonly companyUserEmployeeEvent: CompanyUserEmployeeEventService;
    public readonly companyUserEmployeeEventMeeting: CompanyUserEmployeeEventMeetingService;
    public readonly companyUserEmployeeEventNote: CompanyUserEmployeeEventNoteService;
    public readonly companyUserEmployeeEvents: CompanyUserEmployeeEventsService;
    public readonly companyUserEmployeeEventsMeetings: CompanyUserEmployeeEventsMeetingsService;
    public readonly companyUserEmployeeEventsNotes: CompanyUserEmployeeEventsNotesService;
    public readonly companyUserEmployeeEventsTasks: CompanyUserEmployeeEventsTasksService;
    public readonly companyUserEmployeeEventTask: CompanyUserEmployeeEventTaskService;
    public readonly companyUserFull: CompanyUserFullService;
    public readonly companyUserPermissions: CompanyUserPermissionsService;
    public readonly companyUserProfile: CompanyUserProfileService;
    public readonly companyUserProfileCommitment: CompanyUserProfileCommitmentService;
    public readonly companyUserProfileEducation: CompanyUserProfileEducationService;
    public readonly companyUserProfileEmployer: CompanyUserProfileEmployerService;
    public readonly companyUserProfileExtSkill: CompanyUserProfileExtSkillService;
    public readonly companyUserProfileImport: CompanyUserProfileImportService;
    public readonly companyUserProfileLanguage: CompanyUserProfileLanguageService;
    public readonly companyUserProfileLanguages: CompanyUserProfileLanguagesService;
    public readonly companyUserProfilePresentation: CompanyUserProfilePresentationService;
    public readonly companyUserProfileReference: CompanyUserProfileReferenceService;
    public readonly companyUserProfiles: CompanyUserProfilesService;
    public readonly companyUserProfileSkill: CompanyUserProfileSkillService;
    public readonly companyUserProfileTraining: CompanyUserProfileTrainingService;
    public readonly companyUserProfileWorkExperience: CompanyUserProfileWorkExperienceService;
    public readonly companyUserResume: CompanyUserResumeService;
    public readonly companyUserResumes: CompanyUserResumesService;
    public readonly companyUserRoles: CompanyUserRolesService;
    public readonly companyUsers: CompanyUsersService;
    public readonly companyUsersExtended: CompanyUsersExtendedService;
    public readonly companyUserSkill: CompanyUserSkillService;
    public readonly companyUserSkills: CompanyUserSkillsService;
    public readonly companyUserSubcontractor: CompanyUserSubcontractorService;
    public readonly companyUserSubcontractorEvent: CompanyUserSubcontractorEventService;
    public readonly companyUserSubcontractorEventMeeting: CompanyUserSubcontractorEventMeetingService;
    public readonly companyUserSubcontractorEventNote: CompanyUserSubcontractorEventNoteService;
    public readonly companyUserSubcontractorEvents: CompanyUserSubcontractorEventsService;
    public readonly companyUserSubcontractorEventsMeetings: CompanyUserSubcontractorEventsMeetingsService;
    public readonly companyUserSubcontractorEventsNotes: CompanyUserSubcontractorEventsNotesService;
    public readonly companyUserSubcontractorEventsTasks: CompanyUserSubcontractorEventsTasksService;
    public readonly companyUserSubcontractorEventTask: CompanyUserSubcontractorEventTaskService;
    public readonly companyUserSubcontractorFileAttachment: CompanyUserSubcontractorFileAttachmentService;
    public readonly companyUserSubcontractorFileAttachments: CompanyUserSubcontractorFileAttachmentsService;
    public readonly companyUserSubcontractorRoles: CompanyUserSubcontractorRolesService;
    public readonly companyUserSubcontractors: CompanyUserSubcontractorsService;
    public readonly companyUserTags: CompanyUserTagsService;
    public readonly companyUserTeams: CompanyUserTeamsService;
    public readonly companyWebhook: CompanyWebhookService;
    public readonly companyWebhooks: CompanyWebhooksService;
    public readonly dynamicCompanyUserResume: DynamicCompanyUserResumeService;
    public readonly keywordSearch: KeywordSearchService;
    public readonly mentions: MentionsService;
    public readonly partners: PartnersService;
    public readonly project: ProjectService;
    public readonly projectAssignment: ProjectAssignmentService;
    public readonly projectAssignmentMember: ProjectAssignmentMemberService;
    public readonly projectAssignments: ProjectAssignmentsService;
    public readonly projectAssignmentSkills: ProjectAssignmentSkillsService;
    public readonly projectEvent: ProjectEventService;
    public readonly projectEvents: ProjectEventsService;
    public readonly projectEventsMeeting: ProjectEventsMeetingService;
    public readonly projectEventsMeetings: ProjectEventsMeetingsService;
    public readonly projectEventsNote: ProjectEventsNoteService;
    public readonly projectEventsNotes: ProjectEventsNotesService;
    public readonly projectEventsTask: ProjectEventsTaskService;
    public readonly projectEventsTasks: ProjectEventsTasksService;
    public readonly projectPipelines: ProjectPipelinesService;
    public readonly projectReference: ProjectReferenceService;
    public readonly projectReferences: ProjectReferencesService;
    public readonly projects: ProjectsService;
    public readonly projectTags: ProjectTagsService;
    public readonly recruitmentSources: RecruitmentSourcesService;
    public readonly searchCompanyCandidate: SearchCompanyCandidateService;
    public readonly searchCompanyCustomerContact: SearchCompanyCustomerContactService;
    public readonly searchCompanyCustomers: SearchCompanyCustomersService;
    public readonly searchCompanyUser: SearchCompanyUserService;
    public readonly searchProject: SearchProjectService;
    public readonly skillSearch: SkillSearchService;
    public readonly skillSearchTerm: SkillSearchTermService;
    public readonly request: BaseHttpRequest;
    constructor(config?: Partial<OpenAPIConfig>, HttpRequest: HttpRequestConstructor = AxiosHttpRequest) {
        this.request = new HttpRequest({
            BASE: config?.BASE ?? 'https://api.cinode.com',
            VERSION: config?.VERSION ?? '0.1',
            WITH_CREDENTIALS: config?.WITH_CREDENTIALS ?? false,
            CREDENTIALS: config?.CREDENTIALS ?? 'include',
            TOKEN: config?.TOKEN,
            USERNAME: config?.USERNAME,
            PASSWORD: config?.PASSWORD,
            HEADERS: config?.HEADERS,
            ENCODE_PATH: config?.ENCODE_PATH,
        });
        this.absence = new AbsenceService(this.request);
        this.absences = new AbsencesService(this.request);
        this.absenceType = new AbsenceTypeService(this.request);
        this.availability = new AvailabilityService(this.request);
        this.company = new CompanyService(this.request);
        this.companyAddressUsers = new CompanyAddressUsersService(this.request);
        this.companyCandidate = new CompanyCandidateService(this.request);
        this.companyCandidateEvent = new CompanyCandidateEventService(this.request);
        this.companyCandidateEventMeeting = new CompanyCandidateEventMeetingService(this.request);
        this.companyCandidateEventMeetings = new CompanyCandidateEventMeetingsService(this.request);
        this.companyCandidateEventNote = new CompanyCandidateEventNoteService(this.request);
        this.companyCandidateEventNotes = new CompanyCandidateEventNotesService(this.request);
        this.companyCandidateEvents = new CompanyCandidateEventsService(this.request);
        this.companyCandidateEventTask = new CompanyCandidateEventTaskService(this.request);
        this.companyCandidateEventTasks = new CompanyCandidateEventTasksService(this.request);
        this.companyCandidateFileAttachment = new CompanyCandidateFileAttachmentService(this.request);
        this.companyCandidateFileAttachments = new CompanyCandidateFileAttachmentsService(this.request);
        this.companyCandidatePipelines = new CompanyCandidatePipelinesService(this.request);
        this.companyCandidates = new CompanyCandidatesService(this.request);
        this.companyCandidateSkills = new CompanyCandidateSkillsService(this.request);
        this.companyCandidateUriAttachment = new CompanyCandidateUriAttachmentService(this.request);
        this.companyCandidateUriAttachments = new CompanyCandidateUriAttachmentsService(this.request);
        this.companyCandidateUser = new CompanyCandidateUserService(this.request);
        this.companyCapabilities = new CompanyCapabilitiesService(this.request);
        this.companyCurrencies = new CompanyCurrenciesService(this.request);
        this.companyCustomer = new CompanyCustomerService(this.request);
        this.companyCustomerAddress = new CompanyCustomerAddressService(this.request);
        this.companyCustomerContact = new CompanyCustomerContactService(this.request);
        this.companyCustomerContacts = new CompanyCustomerContactsService(this.request);
        this.companyCustomerContactTags = new CompanyCustomerContactTagsService(this.request);
        this.companyCustomerEvent = new CompanyCustomerEventService(this.request);
        this.companyCustomerEvents = new CompanyCustomerEventsService(this.request);
        this.companyCustomerEventsMeeting = new CompanyCustomerEventsMeetingService(this.request);
        this.companyCustomerEventsMeetings = new CompanyCustomerEventsMeetingsService(this.request);
        this.companyCustomerEventsNote = new CompanyCustomerEventsNoteService(this.request);
        this.companyCustomerEventsNotes = new CompanyCustomerEventsNotesService(this.request);
        this.companyCustomerEventsTask = new CompanyCustomerEventsTaskService(this.request);
        this.companyCustomerEventsTasks = new CompanyCustomerEventsTasksService(this.request);
        this.companyCustomerFileAttachment = new CompanyCustomerFileAttachmentService(this.request);
        this.companyCustomerManagers = new CompanyCustomerManagersService(this.request);
        this.companyCustomers = new CompanyCustomersService(this.request);
        this.companyCustomersExtended = new CompanyCustomersExtendedService(this.request);
        this.companyCustomerTags = new CompanyCustomerTagsService(this.request);
        this.companyImage = new CompanyImageService(this.request);
        this.companyImages = new CompanyImagesService(this.request);
        this.companyManagers = new CompanyManagersService(this.request);
        this.companyProfiles = new CompanyProfilesService(this.request);
        this.companyProjectFileAttachment = new CompanyProjectFileAttachmentService(this.request);
        this.companyRecruitmentManagers = new CompanyRecruitmentManagersService(this.request);
        this.companyResumes = new CompanyResumesService(this.request);
        this.companySubcontractorGroup = new CompanySubcontractorGroupService(this.request);
        this.companySubcontractorGroupMembers = new CompanySubcontractorGroupMembersService(this.request);
        this.companySubcontractorGroups = new CompanySubcontractorGroupsService(this.request);
        this.companyTag = new CompanyTagService(this.request);
        this.companyTags = new CompanyTagsService(this.request);
        this.companyTeam = new CompanyTeamService(this.request);
        this.companyTeamManagers = new CompanyTeamManagersService(this.request);
        this.companyTeamMember = new CompanyTeamMemberService(this.request);
        this.companyTeamMembers = new CompanyTeamMembersService(this.request);
        this.companyTeams = new CompanyTeamsService(this.request);
        this.companyTeamUsers = new CompanyTeamUsersService(this.request);
        this.companyUser = new CompanyUserService(this.request);
        this.companyUserConvert = new CompanyUserConvertService(this.request);
        this.companyUserEmployeeEvent = new CompanyUserEmployeeEventService(this.request);
        this.companyUserEmployeeEventMeeting = new CompanyUserEmployeeEventMeetingService(this.request);
        this.companyUserEmployeeEventNote = new CompanyUserEmployeeEventNoteService(this.request);
        this.companyUserEmployeeEvents = new CompanyUserEmployeeEventsService(this.request);
        this.companyUserEmployeeEventsMeetings = new CompanyUserEmployeeEventsMeetingsService(this.request);
        this.companyUserEmployeeEventsNotes = new CompanyUserEmployeeEventsNotesService(this.request);
        this.companyUserEmployeeEventsTasks = new CompanyUserEmployeeEventsTasksService(this.request);
        this.companyUserEmployeeEventTask = new CompanyUserEmployeeEventTaskService(this.request);
        this.companyUserFull = new CompanyUserFullService(this.request);
        this.companyUserPermissions = new CompanyUserPermissionsService(this.request);
        this.companyUserProfile = new CompanyUserProfileService(this.request);
        this.companyUserProfileCommitment = new CompanyUserProfileCommitmentService(this.request);
        this.companyUserProfileEducation = new CompanyUserProfileEducationService(this.request);
        this.companyUserProfileEmployer = new CompanyUserProfileEmployerService(this.request);
        this.companyUserProfileExtSkill = new CompanyUserProfileExtSkillService(this.request);
        this.companyUserProfileImport = new CompanyUserProfileImportService(this.request);
        this.companyUserProfileLanguage = new CompanyUserProfileLanguageService(this.request);
        this.companyUserProfileLanguages = new CompanyUserProfileLanguagesService(this.request);
        this.companyUserProfilePresentation = new CompanyUserProfilePresentationService(this.request);
        this.companyUserProfileReference = new CompanyUserProfileReferenceService(this.request);
        this.companyUserProfiles = new CompanyUserProfilesService(this.request);
        this.companyUserProfileSkill = new CompanyUserProfileSkillService(this.request);
        this.companyUserProfileTraining = new CompanyUserProfileTrainingService(this.request);
        this.companyUserProfileWorkExperience = new CompanyUserProfileWorkExperienceService(this.request);
        this.companyUserResume = new CompanyUserResumeService(this.request);
        this.companyUserResumes = new CompanyUserResumesService(this.request);
        this.companyUserRoles = new CompanyUserRolesService(this.request);
        this.companyUsers = new CompanyUsersService(this.request);
        this.companyUsersExtended = new CompanyUsersExtendedService(this.request);
        this.companyUserSkill = new CompanyUserSkillService(this.request);
        this.companyUserSkills = new CompanyUserSkillsService(this.request);
        this.companyUserSubcontractor = new CompanyUserSubcontractorService(this.request);
        this.companyUserSubcontractorEvent = new CompanyUserSubcontractorEventService(this.request);
        this.companyUserSubcontractorEventMeeting = new CompanyUserSubcontractorEventMeetingService(this.request);
        this.companyUserSubcontractorEventNote = new CompanyUserSubcontractorEventNoteService(this.request);
        this.companyUserSubcontractorEvents = new CompanyUserSubcontractorEventsService(this.request);
        this.companyUserSubcontractorEventsMeetings = new CompanyUserSubcontractorEventsMeetingsService(this.request);
        this.companyUserSubcontractorEventsNotes = new CompanyUserSubcontractorEventsNotesService(this.request);
        this.companyUserSubcontractorEventsTasks = new CompanyUserSubcontractorEventsTasksService(this.request);
        this.companyUserSubcontractorEventTask = new CompanyUserSubcontractorEventTaskService(this.request);
        this.companyUserSubcontractorFileAttachment = new CompanyUserSubcontractorFileAttachmentService(this.request);
        this.companyUserSubcontractorFileAttachments = new CompanyUserSubcontractorFileAttachmentsService(this.request);
        this.companyUserSubcontractorRoles = new CompanyUserSubcontractorRolesService(this.request);
        this.companyUserSubcontractors = new CompanyUserSubcontractorsService(this.request);
        this.companyUserTags = new CompanyUserTagsService(this.request);
        this.companyUserTeams = new CompanyUserTeamsService(this.request);
        this.companyWebhook = new CompanyWebhookService(this.request);
        this.companyWebhooks = new CompanyWebhooksService(this.request);
        this.dynamicCompanyUserResume = new DynamicCompanyUserResumeService(this.request);
        this.keywordSearch = new KeywordSearchService(this.request);
        this.mentions = new MentionsService(this.request);
        this.partners = new PartnersService(this.request);
        this.project = new ProjectService(this.request);
        this.projectAssignment = new ProjectAssignmentService(this.request);
        this.projectAssignmentMember = new ProjectAssignmentMemberService(this.request);
        this.projectAssignments = new ProjectAssignmentsService(this.request);
        this.projectAssignmentSkills = new ProjectAssignmentSkillsService(this.request);
        this.projectEvent = new ProjectEventService(this.request);
        this.projectEvents = new ProjectEventsService(this.request);
        this.projectEventsMeeting = new ProjectEventsMeetingService(this.request);
        this.projectEventsMeetings = new ProjectEventsMeetingsService(this.request);
        this.projectEventsNote = new ProjectEventsNoteService(this.request);
        this.projectEventsNotes = new ProjectEventsNotesService(this.request);
        this.projectEventsTask = new ProjectEventsTaskService(this.request);
        this.projectEventsTasks = new ProjectEventsTasksService(this.request);
        this.projectPipelines = new ProjectPipelinesService(this.request);
        this.projectReference = new ProjectReferenceService(this.request);
        this.projectReferences = new ProjectReferencesService(this.request);
        this.projects = new ProjectsService(this.request);
        this.projectTags = new ProjectTagsService(this.request);
        this.recruitmentSources = new RecruitmentSourcesService(this.request);
        this.searchCompanyCandidate = new SearchCompanyCandidateService(this.request);
        this.searchCompanyCustomerContact = new SearchCompanyCustomerContactService(this.request);
        this.searchCompanyCustomers = new SearchCompanyCustomersService(this.request);
        this.searchCompanyUser = new SearchCompanyUserService(this.request);
        this.searchProject = new SearchProjectService(this.request);
        this.skillSearch = new SkillSearchService(this.request);
        this.skillSearchTerm = new SkillSearchTermService(this.request);
    }
}

